{% set name = "zope.event" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bac440d8d9891b4068e2b5a2c5e2c9765a9df762944bda6955f96bb9b91e67cd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # https://github.com/zopefoundation/zope.event/blob/5.0/setup.py#L69
    - setuptools

test:
  imports:
    - zope
    - zope.event
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv --pyargs zope.event.tests

about:
  home: https://github.com/zopefoundation/zope.event
  license: ZPL-2.1
  license_family: OTHER
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  summary: Event publishing / dispatch, used by Zope Component Architecture
  description: |
    This package provides a simple event system on which application-specific
    event systems can be built. For example, a type-based event dispatching
    system that builds on zope.interface can be found in zope.component. A
    simpler system is distributed with this package and is described in
    Class-based event handlers.
  doc_url: https://zopeevent.readthedocs.io/
  dev_url: https://github.com/zopefoundation/zope.event


extra:
  recipe-maintainers:
    - mingwandroid
