{% set name = "zope.event" %}
{% set version = "6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('.', '_')}}-{{ version }}.tar.gz
  sha256: 6052a3e0cb8565d3d4ef1a3a7809336ac519bc4fe38398cb8d466db09adef4f0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=78.1.1,<81
    - wheel
  run:
    - python

test:
  imports:
    - zope
    - zope.event
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv --pyargs zope.event.tests

about:
  home: https://github.com/zopefoundation/zope.event
  license: ZPL-2.1
  license_family: OTHER
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  summary: Event publishing / dispatch, used by Zope Component Architecture
  description: |
    This package provides a simple event system on which application-specific
    event systems can be built. For example, a type-based event dispatching
    system that builds on zope.interface can be found in zope.component. A
    simpler system is distributed with this package and is described in
    Class-based event handlers.
  doc_url: https://zopeevent.readthedocs.io
  dev_url: https://github.com/zopefoundation/zope.event


extra:
  recipe-maintainers:
    - mingwandroid
